---
- hosts: localhost
  remote_user: ubuntu
  tasks:
     - name: Create Folder
       file:
        path: /home/ubuntu/tomcat
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
