---
- hosts: 172.31.27.92
  sudo: yes
  tasks:
    - name: Create test dir172.31.27.92ectory
      file:
        path: /home/ubuntu/test4-CookBook
        state: directory 
        mode: 0755
        owner: ubuntu

    



       

